apiVersion: apps/v1
kind: Deployment
metadata:
  name: temporal-worker
  namespace: temporal-metrics
  labels:
    app: temporal-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: temporal-worker
  template:
    metadata:
      labels:
        app: temporal-worker
    spec:
      containers:
        - name: worker
          image: antmendoza/temporal_worker_for_ts-sdk-metrics:v0.1.0
          imagePullPolicy: Always
          command: ["node", "lib/worker.js"]
          env:
            - name: OTEL_EXPORTER_OTLP_ENDPOINT
              value: http://otel-collector.temporal-metrics.svc.cluster.local:4317
            - name: OTEL_SERVICE_NAME
              value: temporal-worker-a
            - name: OTEL_RESOURCE_ATTRIBUTES
              value: deployment.environment=dev
            - name: TEMPORAL_PROFILE
              value: prod
            - name: TEMPORAL_CONFIG_FILE
              value: /app/temporal.toml
          volumeMounts:
            - name: temporal-config
              mountPath: /app/temporal.toml
              subPath: temporal.toml
              readOnly: true
          resources:
            requests:
              cpu: "500m"
              memory: "256Mi"
            limits:
              cpu: "1"
              memory: "512Mi"
      volumes:
        - name: temporal-config
          secret:
            secretName: temporal-config
