version: "3.5"
services:

  otel-collector:
    image: otel/opentelemetry-collector-contrib
    volumes:
      - ./collector.yaml:/etc/otelcol-contrib/config.yaml
    ports:
      - 1888:1888 # pprof extension
      - 8888:8888 # Prometheus metrics exposed by the Collector
      - 8889:8889 # Prometheus exporter metrics
      - 13133:13133 # health_check extension
      - 4317:4317 # OTLP gRPC receiver
      - 4318:4318 # OTLP http receiver
      - 55679:55679 # zpages extension
    env_file:
      - .env
    networks:
      - temporal-network

  worker-a:
    build:
      context: ..
      dockerfile: Dockerfile
    command: ["node", "lib/worker.js"]
    depends_on:
      - otel-collector
    volumes:
      - ./temporal.toml:/app/temporal.toml:ro
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=temporal-worker-a
      - OTEL_RESOURCE_ATTRIBUTES=deployment.environment=antmendoza-dev
    env_file:
      - .env
    # load     cpus from env file
    cpus: 1
    mem_limit: 512m
    networks:
      - temporal-network
    # Uncomment if you need to connect to a Temporal server running on the host
    # extra_hosts:
    #   - "host.docker.internal:host-gateway"
    restart:
      always

  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    ports:
      - "8080:8080"
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:ro
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
    networks:
      - temporal-network
    restart:
      unless-stopped



networks:
  temporal-network:
    driver: bridge
